export const PATH = {
    HOME: '/',
    DETAIL: '/detail',
    CATEGORY: '/category',
    CART: '/cart',
    LOGIN: '/login',
    REGISTER: '/register',
    ADMIN: '/admin',
    ADMIN_CATEGORY: '/admin/category',
    ADMIN_PRODUCTS: '/admin/products',
    ADMIN_USERS: '/admin/users',
    ADD_CATEGORY: '/admin/category/add',
    UPDATE_CATEGORY: '/admin/category/update',
    ADD_PRODUCTS: '/admin/products/add',
    UPDATE_PRODUCTS: '/admin/products/update',
    ADD_USERS: '/admin/users/add',
}